class UserNotFoundError(Exception):
    ...

class UserNotActiveError(Exception):
    ...

class IncorrectPasswordError(Exception):
    ...

class InvalidSessionUUIDError(Exception):
    ...

class ExpiredSessionError(Exception):
    ...
