from ..._module_types import NewRecord

base_user: NewRecord.User = {
    'name': 'IACele',
    'login': 'iacele',
    'active': False,
}
initial_data = [
    (
        'base.model',
        [
            {
                'model': 'base.model',
                'name': 'base_model',
                'label': 'Modelos',
                'description': 'Este modelo define los modelos de la base de datos.',
                'state': 'base',
            },
            {
                'model': 'base.model.field',
                'name': 'base_model_field',
                'label': 'Campos',
                'description': 'Este modelo define los campos de la base de datos.',
                'state': 'base',
            },
            {
                'model': 'base.model.field.selection',
                'name': 'base_model_field_selection',
                'label': 'Tipo de selección',
                'description': 'Este modelo define los valores de selección para usarse como tipo de dato en campos de modelos.',
                'state': 'base',
            },
            {
                'model': 'base.users',
                'name': 'base_users',
                'label': 'Usuarios',
                'description': 'Este modelo define la estructura de usuarios en la base de datos',
                'state': 'base',
            },
        ],
    ),
    (
        'base.model.field',
        [
            {
                'name': 'id',
                'label': 'ID',
                'ttype': 'integer',
                'model_id': 1,
                'nullable': False,
                'unique': True,
                'state': 'base',
            },
            {
                'name': 'name',
                'label': 'Nombre',
                'ttype': 'char',
                'model_id': 1,
                'is_required': True,
                'state': 'base',
            },
            {
                'name': 'create_date',
                'label': 'Fecha de creación',
                'ttype': 'datetime',
                'model_id': 1,
                'nullable': False,
                'state': 'base',
            },
            {
                'name': 'write_date',
                'label': 'Fecha de modificación',
                'ttype': 'datetime',
                'model_id': 1,
                'nullable': False,
                'state': 'base',
            },
            {
                'name': 'model',
                'label': 'Modelo',
                'ttype': 'char',
                'model_id': 1,
                'nullable': False,
                'unique': True,
                'is_required': True,
                'state': 'base',
            },
            {
                'name': 'label',
                'label': 'Etiqueta',
                'ttype': 'char',
                'model_id': 1,
                'nullable': False,
                'is_required': True,
                'state': 'base',
            },
            {
                'name': 'description',
                'label': 'Descripción',
                'ttype': 'text',
                'model_id': 1,
                'state': 'base',
            },
            {
                'name': 'state',
                'label': 'Tipo de modelo',
                'ttype': 'selection',
                'model_id': 1,
                'nullable': False,
                'default_value': 'generic',
                'state': 'base',
            },
            {
                'name': 'id',
                'label': 'ID',
                'ttype': 'integer',
                'model_id': 2,
                'nullable': False,
                'unique': True,
                'state': 'base',
            },
            {
                'name': 'name',
                'label': 'Nombre',
                'ttype': 'char',
                'model_id': 2,
                'is_required': True,
                'state': 'base',
            },
            {
                'name': 'create_date',
                'label': 'Fecha de creación',
                'ttype': 'datetime',
                'model_id': 2,
                'nullable': False,
                'state': 'base',
            },
            {
                'name': 'write_date',
                'label': 'Fecha de modificación',
                'ttype': 'datetime',
                'model_id': 2,
                'nullable': False,
                'state': 'base',
            },
            {
                'name': 'model_id',
                'label': 'Modelo',
                'ttype': 'many2one',
                'model_id': 2,
                'nullable': False,
                'is_required': True,
                'related_model_id': 1,
                'state': 'base',
            },
            {
                'name': 'label',
                'label': 'Etiqueta de campo',
                'ttype': 'char',
                'model_id': 2,
                'nullable': False,
                'unique': True,
                'is_required': True,
                'state': 'base',
            },
            {
                'name': 'ttype',
                'label': 'Tipo',
                'ttype': 'selection',
                'model_id': 2,
                'nullable': False,
                'is_required': True,
                'state': 'base',
            },
            {
                'name': 'nullable',
                'label': 'Nulo',
                'ttype': 'boolean',
                'model_id': 2,
                'default_value': True,
                'state': 'base',
            },
            {
                'name': 'is_required',
                'label': 'Requerido',
                'ttype': 'boolean',
                'model_id': 2,
                'default_value': False,
                'state': 'base',
            },
            {
                'name': 'default_value',
                'label': 'Valor prestablecido',
                'ttype': 'char',
                'model_id': 2,
                'nullable': True,
                'state': 'base',
            },
            {
                'name': 'unique',
                'label': 'Es valor único',
                'ttype': 'boolean',
                'model_id': 2,
                'default_value': False,
                'state': 'base',
            },
            {
                'name': 'help_info',
                'label': 'Información de ayuda',
                'ttype': 'text',
                'model_id': 2,
                'state': 'base',
            },
            {
                'name': 'related_model_id',
                'label': 'Modelo de relación',
                'ttype': 'many2one',
                'model_id': 2,
                'related_model_id': 1,
                'state': 'base',
            },
            {
                'name': 'related_field',
                'label': 'Campo relacionado',
                'ttype': 'char',
                'model_id': 2,
                'state': 'base',
            },
            {
                'name': 'state',
                'label': 'Tipo de campo',
                'ttype': 'selection',
                'model_id': 2,
                'nullable': False,
                'default_value': 'generic',
                'state': 'base',
            },
            {
                'name': 'id',
                'label': 'ID',
                'ttype': 'integer',
                'model_id': 3,
                'nullable': False,
                'unique': True,
                'state': 'base',
            },
            {
                'name': 'name',
                'label': 'Nombre',
                'ttype': 'char',
                'model_id': 3,
                'is_required': True,
                'state': 'base',
            },
            {
                'name': 'create_date',
                'label': 'Fecha de creación',
                'ttype': 'datetime',
                'model_id': 3,
                'nullable': False,
                'state': 'base',
            },
            {
                'name': 'write_date',
                'label': 'Fecha de modificación',
                'ttype': 'datetime',
                'model_id': 3,
                'nullable': False,
                'state': 'base',
            },
            {
                'name': 'label',
                'label': 'Etiqueta',
                'ttype': 'char',
                'model_id': 3,
                'is_required': True,
                'state': 'base',
            },
            {
                'name': 'field_id',
                'label': 'Campo',
                'ttype': 'many2one',
                'model_id': 3,
                'related_model_id': 2,
                'related_field': 'selection_ids',
                'is_required': True,
                'state': 'base',
            },
            {
                'name': 'id',
                'label': 'ID',
                'ttype': 'integer',
                'model_id': 4,
                'nullable': False,
                'unique': True,
                'state': 'base',
            },
            {
                'name': 'name',
                'label': 'Nombre',
                'ttype': 'char',
                'model_id': 4,
                'is_required': True,
                'state': 'base',
            },
            {
                'name': 'create_date',
                'label': 'Fecha de creación',
                'ttype': 'datetime',
                'model_id': 4,
                'nullable': False,
                'state': 'base',
            },
            {
                'name': 'write_date',
                'label': 'Fecha de modificación',
                'ttype': 'datetime',
                'model_id': 4,
                'nullable': False,
                'state': 'base',
            },
            {
                'name': 'login',
                'label': 'Correo',
                'ttype': 'char',
                'model_id': 4,
                'nullable': False,
                'unique': True,
                'is_required': True,
                'state': 'base',
            },
            {
                'name': 'password',
                'label': 'Contraseña',
                'ttype': 'char',
                'model_id': 4,
                'nullable': False,
                'default_value': '[default_function]',
                'state': 'base',
            },
            {
                'name': 'odoo_id',
                'label': 'ID de Odoo',
                'ttype': 'integer',
                'model_id': 4,
                'state': 'base',
            },
            {
                'name': 'active',
                'label': 'Activo',
                'ttype': 'boolean',
                'model_id': 4,
                'nullable': False,
                'default_value': True,
                'state': 'base',
            },
            {
                'name': 'sync',
                'label': 'Sincronizar',
                'ttype': 'boolean',
                'model_id': 4,
                'nullable': False,
                'default_value': True,
                'state': 'base',
            },
        ],
    ),
    (
        'base.model.field',
        [
            {
                'name': 'field_ids',
                'label': 'Campos',
                'ttype': 'one2many',
                'model_id': 1,
                'related_model_id': 2,
                'related_field': 'model_id',
                'state': 'base',
            },
            {
                'name': 'related_field_ids',
                'label': 'Campos relacionados',
                'ttype': 'one2many',
                'model_id': 1,
                'related_model_id': 2,
                'related_field': 'related_model_id',
                'state': 'base',
            }
        ]
    ),
    (
        'base.model.field.selection',
        [
            {
                'name': 'base',
                'field_id': 8,
                'label': 'Campo base',
            },
            {
                'name': 'generic',
                'field_id': 8,
                'label': 'Campo genérico',
            },
            {
                'name': 'integer',
                'field_id': 15,
                'label': 'Entero',
            },
            {
                'name': 'char',
                'field_id': 15,
                'label': 'Caracter',
            },
            {
                'name': 'float',
                'field_id': 15,
                'label': 'Flotante',
            },
            {
                'name': 'boolean',
                'field_id': 15,
                'label': 'Booleano',
            },
            {
                'name': 'date',
                'field_id': 15,
                'label': 'Fecha',
            },
            {
                'name': 'datetime',
                'field_id': 15,
                'label': 'Fecha y hora',
            },
            {
                'name': 'time',
                'field_id': 15,
                'label': 'Tiempo',
            },
            {
                'name': 'file',
                'field_id': 15,
                'label': 'Archivo',
            },
            {
                'name': 'text',
                'field_id': 15,
                'label': 'Texto largo',
            },
            {
                'name': 'selection',
                'field_id': 15,
                'label': 'Selección',
            },
            {
                'name': 'many2one',
                'field_id': 15,
                'label': 'Muchos a uno',
            },
            {
                'name': 'one2many',
                'field_id': 15,
                'label': 'Uno a muchos',
            },
            {
                'name': 'many2one',
                'field_id': 15,
                'label': 'Muchos a muchos',
            },
            {
                'name': 'base',
                'field_id': 23,
                'label': 'Campo base',
            },
            {
                'name': 'generic',
                'field_id': 23,
                'label': 'Campo genérico',
            },
        ],
    ),
    (
        'base.model.field',
        [
            {
                'name': 'selection_ids',
                'label': 'Valores de selección',
                'ttype': 'one2many',
                'model_id': 2,
                'state': 'base',
                'related_model_id': 3,
                'related_field': 'field_id',
            },
        ]
    ),
]
